### ISSUE TITLE
connHandler could it close the connection ?

### ISSUE THREAD

**Issue by luistrigueiros** [sczyh30/vertx-blueprint-todo-backend#2]
Hi firstly thank you for the blueprint tutorial I have been reading a it is great love it.
Question the jdbc todo service has this connHandler that is wrapping every call done by service handler methods, why does this method not close the connection ?

Tx, Oscar

**Comment by sczyh30** [comment]
Hi, the APIs in **Vert.x JDBC** are all asynchronous(though backed by worker pool) and any operations we do on the `connection` is **asynchronous** (e.g. `execute`). So we have to wait for closing the connection after the operation result is prepared. That's why `connHandler` method doesn't close the connection as the `handler.handle(connection)` procedure is actually asynchronous.
